[colors.normal]
black = "#f8f4ed"   # bg,      hanbaiyu
red = "#c21f30"     # red,     fengyehong
green = "#12AA9c"   # green,   meidielü
yellow = "#806332"  # yellow,  canghuang
blue = "#1661ab"    # blue,    dianqing
magenta = "#ee2c79" # magenta, zijinghong
cyan = "#1e9eb3"    # cyan,    cuilan
white = "#47484c"   # fg0,     waguanhui

[colors.bright]
black = "#e4dfd7"   # bg0,      zhenzhuhui
red = "#f03752"     # red0,     haitanghong
green = "#57c3c2"   # green0,   shilü
yellow = "#fbb957"  # yellow0,  mihuang
blue = "#66a9c9"    # blue0,    jianshilan
magenta = "#ea7293" # magenta0, fengxianhuahong
cyan = "#51c4d3"    # cyan0,    pubulan
white = "#21373d"   # fg,       huilan

[colors.dim]
black = "#f8f4ed"   # bg,      hanbaiyu
red = "#c21f30"     # red,     fengyehong
green = "#12AA9c"   # green,   meidielü
yellow = "#806332"  # yellow,  canghuang
blue = "#1661ab"    # blue,    dianqing
magenta = "#ee2c79" # magenta, zijinghong
cyan = "#1e9eb3"    # cyan,    cuilan
white = "#47484c"   # fg0,     waguanhui

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.footer_bar]
background = "#f8f4ed" # bg
foreground = "#21373d" # fg

[colors.hints.end]
background = "#f03752" # red0
foreground = "#21373d" # fg

[colors.hints.start]
background = "#f03752" # red0
foreground = "#21373d" # fg

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.primary]
background = "#f8f4ed"        # bg
foreground = "#21373d"        # fg
dim_foreground = "#47484c"    # fg0
bright_foreground = "#21373d" # fg

[colors.search.focused_match]
background = "CellForeground"
foreground = "#f8f4ed"        # bg

[colors.search.matches]
background = "#51c4d3" # cyan0
foreground = "#21373d" # fg

[colors.selection]
background = "#e4dfd7"  # bg0
text = "CellForeground"

[colors.vi_mode_cursor]
background = "CellForeground"
text = "#f8f4ed"              # bg
